import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Navbar from "@/components/Navbar/Navbar";
import { ConfigProvider } from "antd";
import Footer from "@/components/Footer/Footer";
import { Toaster } from 'sonner';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: "#D6FD60",           // --color-primary
              colorTextLightSolid: '#003C51', // Button text color
              colorSuccess: "#003C51",       // --color-success
              colorWarning: "#f59e0b",       // --color-warning
              colorError: "#dc2626",         // --color-error
              colorInfo: "#0ea5e9",          // --color-info
              colorTextBase: "#111827",      // --color-text-base
              colorBgBase: "#ffffff",        // --color-bg-base
            },
          }}
        >
          <AntdRegistry>
            <Toaster />
            <Navbar />
            {children}
            <Footer />
          </AntdRegistry>
        </ConfigProvider>
      </body>
    </html>
  );
}
